### ISSUE TITLE
Parsing into Map type at top-level fails

### ISSUE THREAD

**Issue by cjfuller** [cbeust/klaxon#103]
I'm trying to parse some JSON that I'm expecting to conform to the type `Map<String, SomeClass>` at top-level. A simple test case of doing this is:
```
val m: Map<String, String> = Klaxon().parse("""{
    "a": "b"
    }""")!!
```
but this fails with `Couldn't find a suitable constructor for class Map to initialize with {}: null`.

That kind of makes sense because `Map` is an interface, but then if I try to provide a concrete map implementation like `HashMap`, I get errors seemingly from it trying to deal with some of that type's internal properties:
```
val m: HashMap<String, String> = Klaxon().parse("""{
        "a": "b"
        }""")!!
```
gives
```
Exception in thread "main" java.lang.NoSuchFieldException: values
        at java.lang.Class.getDeclaredField(Class.java:2070)
        at com.beust.klaxon.Annotations$Companion.findJsonAnnotation(Annotations.kt:16)
        at com.beust.klaxon.Klaxon$fromJsonObject$1.invoke(Klaxon.kt:265)
        at com.beust.klaxon.Klaxon$fromJsonObject$2.invoke(Klaxon.kt:304)
        at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:342)
```

It works just fine if I try to put a map like this as a property on a class (and I think you already have a test for this):
```
data class MyClass(
    val m: Map<String, String>
)
val c: MyClass = Klaxon().parse("""{
    "m": {"a": "b"}
}""")!!
```
I'm not sure what's different here vs. at top level.

(I've tried this both on the 2.1.2 release as well as on the latest commit 6a426e9, and I get the same result).

Some background on the usecase, in case you're wondering why I don't just want to parse it to a `JsonObject` and then iterate over that to parse out my custom type:

I have two different isolated parts of my codebase I'm working with, one which defines a bunch of types and their associated application logic, and another which is a generic system for persisting objects in my application to storage. The `Map<String, SomeClass>` I'm trying to parse into is only exposed as a type alias (and a bunch of functions that operate on that alias), and I would like to keep the fact that it's a `Map` an implementation detail so that I'm free to modify this in the future. Likewise, my various types don't know about how they are persisted, and I'd like to keep the serialization format an implementation detail that's separate from the core types and internal to the persistence code.

**Comment by cbeust** [comment]
Should be fixed in 2.1.4.

Note that you still need to tell Klaxon how to convert to a `Map`:

```
    fun mapTest() {
        val mapConverter = object: Converter<HashMap<String, Any?>> {
            override fun fromJson(jv: JsonValue): HashMap<String, Any?> = HashMap(jv.obj!!)
            override fun toJson(value: HashMap<String, Any?>) = TODO("not implemented")
        }

        val m: HashMap<String, String> = Klaxon()
                .converter(mapConverter)
                .parse("""{
            "a": "b"
            }""")!!
        assertThat(m["a"]).isEqualTo("b")
    }
```
