### ISSUE TITLE
Converter<T> is used to convert a List<T>

### ISSUE THREAD

**Issue by dvdsgl** [cbeust/klaxon#122]
`Converter<Tuple>` is incorrectly(?) used to convert a `List<Tuple>` when marshaling `TopLevel`:

```kotlin
import com.beust.klaxon.*

val convertTuple = object: Converter<Tuple> {
    override fun toJson(value: Tuple): String? = when (value) {
        is Tuple.IntegerValue -> value.value.toString()
        is Tuple.StringValue  -> value.value
    }

    override fun fromJson(jv: JsonValue): Tuple {
        val x = jv.inside
        return when (x) {
            is Int    -> Tuple.IntegerValue(x)
            is String -> Tuple.StringValue(x)
            else      -> throw IllegalArgumentException("Invalid Tuple")
        }
    }
}

data class TopLevel(val tuples: List<List<Tuple>>)

sealed class Tuple {
    class IntegerValue(val value: Int)  : Tuple()
    class StringValue(val value: String): Tuple()
}

fun main(args: Array<String>) {
    val klaxon = Klaxon().converter(convertTuple)
    val result = klaxon.parse<TopLevel>("""
        {
            "tuples": [[0, "zero"]]
        }
    """)
}
```

For some reason, my converter is a passed a `JsonArray(value=[0, zero])`, resulting in:

```
Exception in thread "main" java.lang.IllegalArgumentException: Invalid Tuple
        at TopLevelKt$convertTuple$1.fromJson(TopLevel.kt:18)
        at TopLevelKt$convertTuple$1.fromJson(TopLevel.kt:7)
        at com.beust.klaxon.DefaultConverter.fromCollection(DefaultConverter.kt:117)
        at com.beust.klaxon.DefaultConverter.convertValue(DefaultConverter.kt:195)
        at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:13)
        at com.beust.klaxon.JsonObjectConverter.retrieveKeyValues(JsonObjectConverter.kt:81)
        at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:28)
        at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:175)
        at com.beust.klaxon.DefaultConverter.convertValue(DefaultConverter.kt:196)
        at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:13)
        at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:273)
        at TopLevelKt.main(TopLevel.kt:40)
```

**Comment by cbeust** [comment]
I think this is the correct behavior: your converter is receiving a `JsonArray` with the elements `[0, "zero"]`. You need to convert that array, not just one element of it.

Feel free to reopen if I've misinterpreted your code.

**Comment by dvdsgl** [comment]
Sorry, I'm not able to reopen.

How would you suggest converting a `JsonArray[0, "zero"]` to a `Tuple` instance? Maybe that will show you the issue.

`Converter<Tuple>.fromJson` is being passed the JSON representation of a `List<Tuple>`, which doesn't make any sense for it to receive since it can only return `Tuple`. This means it must necessarily lost information. I think there is a bug in how converters are resolved for nested collections because this problem goes away for `data class TopLevel(val tuples: List<Tuple>)`.

**Comment by cbeust** [comment]
I'm not quite sure how you could convert an array into a `Tuple` instance (which only contains one value). Can you clarify?

**Comment by cbeust** [comment]
The following test passes:

```
    sealed class Tuple {
        data class IntegerValue(val value: Int)  : Tuple()
        data class StringValue(val value: String): Tuple()
    }

    fun tuples() {
        val klaxon = Klaxon().converter(convertTuple)
        val result = klaxon.parseArray<Tuple>("""
            [0, "zero"]
        """)
        assertThat(result).isEqualTo(listOf(Tuple.IntegerValue(0), Tuple.StringValue("zero")))
```

**Comment by dvdsgl** [comment]
That's my point exactly, you can't do such a conversion, so why is Klaxon attempting to do it? That is the issue.

**Comment by dvdsgl** [comment]
I suspect your parseArray test passes because you're not using nested collections in the general case.
