### ISSUE TITLE
"Couldn't find a suitable constructor" for parsing JSON to subclass

### ISSUE THREAD

**Issue by jnthnwn** [cbeust/klaxon#125]
Sample code:
```
open class Parent(val foo: String)
class Child(foo: String, val bar: String) : Parent(foo)

fun main(args: Array<String>) {
    val jsonString = """
        {
            "foo": "fofo",
            "bar": "baba"
        }
    """

    val parent = Klaxon().parse<Parent>(jsonString)
    val child = Klaxon().parse<Child>(jsonString)
}
```

Running the above code results in the following exception:
```
Exception in thread "main" com.beust.klaxon.KlaxonException: Couldn't find a suitable constructor for class Child to initialize with {bar=baba}: java.lang.IllegalArgumentException No argument provided for a required parameter: parameter #0 foo of fun <init>(kotlin.String, kotlin.String): com.test.Child
	at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:50)
	at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:169)
	at com.beust.klaxon.DefaultConverter.convertValue(DefaultConverter.kt:190)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:13)
	at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:273)
	at com.test.main(Test.kt:20)
```

**Comment by cbeust** [comment]
The issue here is that non public properties are ignored by default by Klaxon, so when you declare:

```
class Child(foo: String, val bar: String) : Parent(foo)
```

Klaxon only see `bar` as a property to match with the JSON document and will ignore `foo`. You can address this by forcing Klaxon to consider that property as well:

```
class Child(@Json(ignored = false) foo: String, val bar: String) : Parent(foo)
```

Having said that, I still had to make a minor fix to Klaxon to accomodate this case, so you'll have to update to 2.1.12 for the code above to work.

FYI, here is your test case, now part of the regression suite:  
https://github.com/cbeust/klaxon/blob/master/src/test/kotlin/com/beust/klaxon/Issue125.kt

**Comment by FreeLineTM** [comment]
I am having the same issue, and setting `@Json(ignored = false)` just gives `This annotation is not applicable to target 'value parameter'`.

**Comment by FreeLineTM** [comment]
Solved it with using `override`, just makes the code very messy though.. Have to declare `@Json(name)` as well, as it doesn't use the annotation from parent class.
