### ISSUE TITLE
no JsonReader.nextLong()?

### ISSUE THREAD

**Issue by mgroth0** [cbeust/klaxon#142]
I have a json string with a long value. I tried reading it with `readInt().toLong()`, but this led to an error

```
java.lang.ClassCastException: java.base/java.lang.Long cannot be cast to java.base/java.lang.Integer
	at com.beust.klaxon.JsonReader$nextInt$1.invoke(JsonReader.kt:17)
	at com.beust.klaxon.JsonReader$nextInt$1.invoke(JsonReader.kt:8)
	at com.beust.klaxon.JsonReader.consumeValue(JsonReader.kt:134)
	at com.beust.klaxon.JsonReader.nextInt(JsonReader.kt:17)
```

consumeValue is private so I could not use `consumeValue { value -> value as Long }`.
I'm using `nextString().toLong()` for now, but is it not wasteful to convert it to a string and back?

**Comment by cbeust** [comment]
Would you mind sending a PR?

**Comment by mgroth0** [comment]
https://github.com/mgroth0/klaxon/pull/1
