### ISSUE TITLE
How do I represent arbitrary data?

### ISSUE THREAD

**Issue by dvdsgl** [cbeust/klaxon#143]
Suppose I need to parse JSON and the only sample I've seen is `{ "thing": {} }`.

I'd like to let the type of `thing` be a dynamic object value, or even `JsonValue`, but I am not sure how to accomplish this.

```kotlin
import com.beust.klaxon.*

data class TopLevel(val thing: Thing)
data class Thing()

val klaxon = Klaxon()
klaxon.parse<TopLevel>("{ \"thing\": {} }")
```

This doesn't work because data classes cannot have empty constructors, and I really want to allow `TopLevel.thing` to be a dynamic object.

I tried `data class TopLevel(val thing: JsonValue)` and it didn't consider that a suitable constructor for the data.

Any suggestions?

---

P.S. I tried to join #klaxon on Slack but a `@jetbrains` email was required.

**Comment by cbeust** [comment]
Anyone can join the Kotlin slack, and from there, the `#klaxon` channel. Try again?

Have you tried to just make `thing` have the type `Map<>`? (that's how I'd expect this to work but I haven't tested)

**Comment by dvdsgl** [comment]
Here is what I see when I try to join slack via the link in the README:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/108197/39657167-38fcb710-4fba-11e8-97ee-59c3d6e96d6a.png">

It says I can only create an account "if [I] have an @jetbrains.com email address".

**Comment by dvdsgl** [comment]
`TopLevel` always has one and only one property named `thing`, so I don't want that to be a map.

To be clear, this is just a minimized example of a general problem of `{}` appearing as a value in some JSON. I don't actually want to parse `{ "thing": {} }`.

**Comment by dvdsgl** [comment]
Oh! I see, yes, I will try making `thing: Map<>`.

**Comment by dvdsgl** [comment]
Here is the sample generated code: https://app2.quicktype.io?share=0N9BPXp8uIPPDZlloq2m

This is sample data from a Reddit API. The `MediaEmbed` type is where I am stuck at the moment. I will try to replace that type with `Map<>` and get back to you. Thanks!

**Comment by dvdsgl** [comment]
So what should I put for the value type of the Map? `Map<String, Any>` and `Map<String, Any?>` do not work:

```
Exception in thread "main" com.beust.klaxon.KlaxonException: Couldn't find a suitable constructor for class TopLevel to initialize with {}: java.lang.IllegalArgumentException No argument provided for a required parameter: parameter #0 data of fun <init>(TopLevelData, kotlin.String): TopLevel
        at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:48)
        at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:200)
        at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:30)
        at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:247)
        at TopLevel$Companion.fromJson(TopLevel.kt:454)
        at quicktype.MainKt.main(main.kt:10)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:61)
        at org.jetbrains.kotlin.runner.Main.run(Main.kt:109)
        at org.jetbrains.kotlin.runner.Main.main(Main.kt:119)
```

**Comment by dvdsgl** [comment]
I could make progress at this point if this were possible:

```kotlin
import com.beust.klaxon.*

data class Top(val thing: JsonValue)

fun main(args: Array<String>) {
	val klaxon = Klaxon()
	val top = klaxon.parse<Top>("{ \"thing\": {} }")!!
	val json = klaxon.toJsonString(top)
	print(json)
}
```

Except I get:

```
Exception in thread "main" java.lang.ClassCastException: kotlin.reflect.jvm.internal.KTypeParameterImpl cannot be cast to kotlin.reflect.KClass
        at com.beust.klaxon.Annotations$Companion.findJsonPaths(Annotations.kt:63)
        at com.beust.klaxon.Annotations$Companion.findJsonPaths(Annotations.kt:71)
        at com.beust.klaxon.Annotations$Companion.findJsonPaths(Annotations.kt:71)
        at com.beust.klaxon.Annotations$Companion.findJsonPaths(Annotations.kt:71)
        at com.beust.klaxon.Annotations$Companion.findJsonPaths(Annotations.kt:71)
        at com.beust.klaxon.Annotations$Companion.findJsonPaths(Annotations.kt:71)
        at com.beust.klaxon.Annotations$Companion.findJsonPaths(Annotations.kt:56)
        at com.beust.klaxon.Klaxon.parser(Klaxon.kt:141)
        at com.beust.klaxon.Klaxon.parser$default(Klaxon.kt:140)
        at quicktype.MainKt.main(main.kt:13)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:61)
        at org.jetbrains.kotlin.runner.Main.run(Main.kt:109)
        at org.jetbrains.kotlin.runner.Main.main(Main.kt:119)
```

I tried making a converter for `JsonValue` with no luck.

**Comment by dvdsgl** [comment]
This works:

```kotlin
import com.beust.klaxon.*

data class Top(val thing: JsonObject)

val convertJsonValue = object: Converter {
    override fun canConvert(cls: Class<*>) = cls == JsonObject::class.java
    override fun toJson(value: Any): String = (value as JsonObject).toJsonString()
    override fun fromJson(jv: JsonValue): Any = jv.inside
}

fun main(args: Array<String>) {
	val klaxon = Klaxon().converter(convertJsonValue)
	val top = klaxon.parse<Top>("{ \"thing\": { \"name\": 6 } }")!!
	val json = klaxon.toJsonString(top)
	print(json)
}
```

**Comment by cbeust** [comment]
Oh nice find!
