### ISSUE TITLE
Cannot parse the empty key

### ISSUE THREAD

**Issue by dvdsgl** [cbeust/klaxon#146]
`{ "": "" }` is valid JSON but Klaxon seems to be unable to parse it:

```kotlin
import com.beust.klaxon.*

private val klaxon = Klaxon()

data class TopLevel (
    @Json(name = "")
    val empty: String
)

fun main(args: Array<String>) {
    val top = klaxon.parse<TopLevel>("""{ "": "" }""")
}
```

```
Exception in thread "main" com.beust.klaxon.KlaxonException: Couldn't find a suitable constructor for class TopLevel to initialize with {}: java.lang.IllegalArgumentException No argument provided for a required parameter: parameter #0 empty of fun <init>(kotlin.String): TopLevel
        at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:48)
        at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:200)
        at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:30)
        at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:247)
        at TopLevel$Companion.fromJson(TopLevel.kt:22)
        at quicktype.MainKt.main(main.kt:10)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:61)
        at org.jetbrains.kotlin.runner.Main.run(Main.kt:109)
        at org.jetbrains.kotlin.runner.Main.main(Main.kt:119)
```

**Comment by dvdsgl** [comment]
Here is the JSON in our test suite that discovered this:

```json
{
  "foo": {
    "_": 123,
    "__": 123,
    "bla": {}
  },
  "bla": {
    "bar": 123
  },
  "!": 123,
  "": {
    "x": 123
  },
  "Empty": {
    "y": 123
  },
  "ThisIsA😜Tough\"\n\nOne": {
    "\"": 123,
    "\n\n\n": 123
  }
}
```

`"ThisIsA😜Tough\"\n\nOne"` also does not work.
