### ISSUE TITLE
Could not parse data for class with generic field

### ISSUE THREAD

**Issue by onebone** [cbeust/klaxon#160]
Klaxon couldn't parse data for class with generic field.

```kotlin
data class A (val a: Int)
data class Parse<T>(val a: T)

Klaxon().parse<Parse<A>>("""{"a":{"a":1}}""")
```

causes

```
java.lang.ClassCastException: kotlin.reflect.jvm.internal.KTypeParameterImpl cannot be cast to kotlin.reflect.KClass
        at com.beust.klaxon.Annotations$Companion.findJsonPaths(Annotations.kt:63)
        at com.beust.klaxon.Annotations$Companion.findJsonPaths(Annotations.kt:56)
        at com.beust.klaxon.Klaxon.parser(Klaxon.kt:141)
        at com.beust.klaxon.Klaxon.parser$default(Klaxon.kt:140)
       ...
```

Tested with Klaxon 3.0.5.

**Comment by vitalybaev** [comment]
Any update here? Having similar issue

**Comment by raderio** [comment]
+1

**Comment by cbeust** [comment]
Looking into this.

Right now I'm struggling trying to recover the fact that `T`'s effective type is `A`, and I can't seem to be able to get this from `kotlin-reflect` so far.

**Comment by Equidamoid** [comment]
Any news? Or maybe workaround ideas? I tried to do something wiht `TypeAdapter`, but lost the battle with Kotlin :(

**Comment by onebone** [comment]
It seems its cause is [type erasure](https://docs.oracle.com/javase/tutorial/java/generics/erasure.html) which is the feature of JVM. It may need some different approach to resolve this.
