### ISSUE TITLE
Should never happen

### ISSUE THREAD

**Issue by karol-202** [cbeust/klaxon#166]
A class with generic type T and a property being a list of T seems to not work with Klaxon because exception `Should never happen` is thrown.

```
class Test<T>(
		val list: MutableList<T> = mutableListOf()
)

fun main(args: Array<String>)
{
	val klaxon = Klaxon()
	val test = Test<String>()
	test.list.add("abc")

	val string = klaxon.toJsonString(test)
	klaxon.parse<Test<String>>(string)
}
```

```
Exception in thread "main" java.lang.IllegalArgumentException: Should never happen
	at com.beust.klaxon.DefaultConverter.fromCollection(DefaultConverter.kt:118)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:30)
	at com.beust.klaxon.JsonObjectConverter.retrieveKeyValues(JsonObjectConverter.kt:104)
	at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:31)
	at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:200)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:31)
	at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:253)
	at MainKt.main(Main.kt:18)
```

**Comment by Octogonapus** [comment]
I am getting a similar exception: https://pastebin.com/TUNEbx3j
With this code on Klaxon version `5.0.5`:
```kotlin
    @Test
    fun `test pair of set conversion`() {
        val foo = "a" to setOf("b", "c")
        Klaxon().let { klaxon ->
            klaxon.parse<Pair<String, Set<String>>>(klaxon.toJsonString(foo))
        }
    }
```

**Comment by cbeust** [comment]
@Octogonapus 

This code works with the current version:

![image](https://user-images.githubusercontent.com/92322/68612127-ac319400-0470-11ea-98db-c590caf8d8b0.png)

**Comment by cbeust** [comment]
@karol-202 

As far as I can tell, there is no way to retrieve the erased type parameter from `kotlin-reflection` right now.
