### ISSUE TITLE
Can't parse classes with declared delegates inside

### ISSUE THREAD

**Issue by ANBAL534** [cbeust/klaxon#180]
```
val x = Klaxon().toJsonString(Character(0))
val char = Klaxon().parse<Character>(x)
```

```
Exception in thread "main" java.lang.ClassCastException: kotlin.reflect.jvm.internal.KTypeParameterImpl cannot be cast to kotlin.reflect.KClass
	at com.beust.klaxon.Annotations$Companion.findJsonPaths(Annotations.kt:72)
	at com.beust.klaxon.Annotations$Companion.findJsonPaths(Annotations.kt:80)
	at com.beust.klaxon.Annotations$Companion.findJsonPaths(Annotations.kt:65)
	at com.beust.klaxon.Klaxon.parser(Klaxon.kt:147)
	at com.beust.klaxon.Klaxon.parser$default(Klaxon.kt:146)
        at com.cmverse.MainKt.main(Main.kt:51)
```

```
import com.beust.klaxon.*
import kotlin.reflect.KProperty

class Character (val id: Int){
    
    var characters = listOf<Character>()
    
    @Json(ignored = true)
    val visibleDelegate = InvalidatableLazyImpl({
        characters.toMutableList()
    })
    @Json(ignored = true)
    val visibleChars: List<Character> by visibleDelegate

}

private object UNINITIALIZED_VALUE
class InvalidatableLazyImpl<T>(private val initializer: () -> T, lock: Any? = null) : Lazy<T> {
    @Volatile private var _value: Any? = UNINITIALIZED_VALUE
    private val lock = lock ?: this
    fun invalidate(){
        _value = UNINITIALIZED_VALUE
    }

    override val value: T
        get() {
            val _v1 = _value
            if (_v1 !== UNINITIALIZED_VALUE) {
                return _v1 as T
            }

            return synchronized(lock) {
                val _v2 = _value
                if (_v2 !== UNINITIALIZED_VALUE) {
                    _v2 as T
                }
                else {
                    val typedValue = initializer()
                    _value = typedValue
                    typedValue
                }
            }
        }


    override fun isInitialized(): Boolean = _value !== UNINITIALIZED_VALUE

    override fun toString(): String = if (isInitialized()) value.toString() else "Lazy value not initialized yet."

    operator fun setValue(any: Any, property: KProperty<*>, t: T) {
        _value = t
    }
}
```

It does also throws the error using a converter as it's thrown before parsing.

Klaxon can convert it to JSON String but can't parse the generated JSON String to the object

**Comment by cbeust** [comment]
Multiple things here, looking at the very first one.

Characters are not handled properly I think right now, is a single character `'c'` valid JSON? Need to look that up.

**Comment by ANBAL534** [comment]
Oh, sorry, my bad, didn't explained that Character class is not the representation for a char variable, but a character as a personage in a movie. A class that I created inside a package in my project

**Comment by ANBAL534** [comment]
Just in case, I changed class name and signature for 
```
class CharacterPlayer (val id: Int,
                       val name: String,
                       val userId: Int)
```

And keeps throwing the error

**Comment by cbeust** [comment]
Try 3.0.8.
