### ISSUE TITLE
Getting java.lang.NoClassDefFoundError on Json Parse

### ISSUE THREAD

**Issue by bshaffer** [cbeust/klaxon#193]
Getting the following exception on a very simple JSON Parse command:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/klaxon/Parser
	at ServerKt.main(server.kt:66)
Caused by: java.lang.ClassNotFoundException: com.beust.klaxon.Parser
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 2 more
```

Here is my full `build.gradle`:

```
buildscript {
    ext.kotlin_version = '1.2.50'

    repositories {
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

plugins {
    id "org.jetbrains.kotlin.jvm" version "1.2.50"
}

sourceSets {
    main.java.srcDirs += 'src'
    test.java.srcDirs += 'test'
}

repositories {
    jcenter()
    mavenCentral()
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib"
    compile group: 'com.google.cloud', name: 'google-cloud-pubsub', version: '1.44.0'
    compile group: 'com.google.cloud', name: 'google-cloud-iot', version: '0.62.0-beta'
    implementation 'com.beust:klaxon:3.0.1'
    testCompile 'junit:junit:4.12'
    // testCompile "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
}

jar {
    manifest {
        attributes 'Main-Class': 'ServerKt'
    }

    // This line of code recursively collects and copies all of a project's files
    // and adds them to the JAR itself. One can extend this task, to skip certain
    // files or particular types at will
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
}

```

And here is my code:

```kt
import com.beust.klaxon.JsonObject
import com.beust.klaxon.Parser

val data: JsonObject = Parser().parse(jsonData) as JsonObject
```

**Comment by bshaffer** [comment]
Well, I was able to fix it by turning `implementation` to `compile` in `build.gradle`
