### ISSUE TITLE
How to parse fields defined in interface or sealed class ?

### ISSUE THREAD

**Issue by smallufo** [cbeust/klaxon#207]
For fields defined in interface , example :  

```kotlin
interface Message {
  val text: String
}

data class MessageReceived(val sender: String,
                           override val text: String) : Message

data class MessageToSend(val recipient: String,
                         override val text: String) : Message



data class Root(val id: Long, val message: Message)

  @Test
  fun testReceived() {
    val jsonString = """
{
  "id":100,
  "message":{
    "sender":"Alice",
    "text":"Hello"
  }
}
    """.trimIndent()
    val root = klaxon.parse<Root>(jsonString)
    logger.info("root = {}" , root)
  }

  @Test
  fun testSending() {
    val jsonString = """
{
  "id":101,
  "message":{
    "recipient":"Bob",
    "text":"Hello"
  }
}
    """.trimIndent()
    val root = klaxon.parse<Root>(jsonString)
    logger.info("root = {}" , root)
  }

```

It throws NoSuchFieldException : 
```
java.lang.NoSuchFieldException: text

	at java.lang.Class.getDeclaredField(Class.java:2070)
	at com.beust.klaxon.Klaxon$findConverterFromClass$1.invoke(Klaxon.kt:196)
	at com.beust.klaxon.Klaxon.findConverterFromClass(Klaxon.kt:205)
	at com.beust.klaxon.JsonObjectConverter.retrieveKeyValues(JsonObjectConverter.kt:103)
	at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:31)
	at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:200)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:31)
	at com.beust.klaxon.JsonObjectConverter.retrieveKeyValues(JsonObjectConverter.kt:104)
	at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:31)
	at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:200)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:31)
	at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:253)
```

And if I define `Message` as sealed class : 
```kotlin
sealed class Message(open val text: String) 

data class MessageReceived(val sender: String,
                           override val text: String) : Message(text)

data class MessageToSend(val recipient: String,
                         override val text: String) : Message(text)
```
It throws `KlaxonException` : 
```
com.beust.klaxon.KlaxonException: Couldn't find a suitable constructor for class Message to initialize with {text=Hello}: java.lang.InstantiationException null

	at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:73)
	at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:200)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:31)
	at com.beust.klaxon.JsonObjectConverter.retrieveKeyValues(JsonObjectConverter.kt:104)
	at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:31)
	at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:200)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:31)
	at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:253)
```

How to correctly handle such situations ?

**Comment by cbeust** [comment]
It's a bug, will look into it.

**Comment by cbeust** [comment]
I fixed this crash, but moving past that, your example can't work because of this:

```
        val root = klaxon.parse<Root>(jsonString)
```

Because `Root` is:

```
      data class Root(val id: Long, val message: Message)
```

Klaxon cannot know which subclass of `Message` to deserialize, so it tries to instantiate a `Message`, and of course, it fails.

You are going to have to do some manual deserialization for that part.
