### ISSUE TITLE
Klaxon throws exceptions after minifying (w/ Proguard)

### ISSUE THREAD

**Issue by Tarpsvo** [cbeust/klaxon#214]
When Klaxon class names were minified, it could not find the DefaultConverter's method `toJson()`.

After adding the following rules to ProGuard, it throws a different exception:
```
-keep public class kotlin.reflect.jvm.internal.impl.** { public *; }
-keep class com.beust.klaxon.** { *; }
-keep interface com.beust.klaxon.** { *; }
```

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bleh.application/com.bleh.application.WhateverActivity}: java.lang.ClassCastException: java.lang.String cannot be cast to com.beust.klaxon.JsonObject
```

The application works perfectly when I turn minify off. Any ideas?

**Comment by cbeust** [comment]
Do you have a stack trace?

**Comment by Tarpsvo** [comment]
Alright, beware of walls of text underneath. Release builds with ProGuard steps shown below.

-----

**Without any Klaxon-related ProGuard configuration.**

```kotlin
2018-11-01 13:42:05.545 32067-32067/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.com.whatever, PID: 32067
    java.lang.IllegalStateException: No BuiltInsLoader implementation was found. Please ensure that the META-INF/services/ is not stripped from your application and that the Java virtual machine is not running under a security manager
        at a.i.b.a.c.a.b$a$a.b(BuiltInsLoader.kt:39)
        at a.i.b.a.c.a.b$a$a.a(BuiltInsLoader.kt:36)
        at a.q.a(LazyJVM.kt:107)
        at a.i.b.a.c.a.b$a.a(Unknown Source:7)
        at a.i.b.a.c.a.g.c(KotlinBuiltIns.java:127)
        at a.i.b.a.c.a.b.e.<init>(JvmBuiltIns.kt:43)
        at a.i.b.a.c.a.b.e.<init>(JvmBuiltIns.kt:18)
        at a.i.b.a.b.j$a.a(RuntimeModuleData.kt:58)
        at a.i.b.a.z.a(moduleByClassLoader.kt:58)
        at a.i.b.a.j$b$a.b(KDeclarationContainerImpl.kt:37)
        at a.i.b.a.j$b$a.a(KDeclarationContainerImpl.kt:34)
        at a.i.b.a.aa$a.a(ReflectProperties.java:92)
        at a.i.b.a.aa$c.a(ReflectProperties.java:31)
        at a.i.b.a.j$b.k(Unknown Source:7)
        at a.i.b.a.g$a$i.b(KClassImpl.kt:47)
        at a.i.b.a.g$a$i.a(KClassImpl.kt:44)
        at a.i.b.a.aa$a.a(ReflectProperties.java:92)
        at a.i.b.a.aa$c.a(ReflectProperties.java:31)
        at a.i.b.a.g$a.a(Unknown Source:7)
        at a.i.b.a.g.h(KClassImpl.kt:179)
        at a.i.b.a.g.j(KClassImpl.kt:188)
        at a.i.b.a.g$a$g.b(KClassImpl.kt:159)
        at a.i.b.a.g$a$g.a(KClassImpl.kt:44)
        at a.i.b.a.aa$a.a(ReflectProperties.java:92)
        at a.i.b.a.aa$c.a(ReflectProperties.java:31)
        at a.i.b.a.g$a.g(Unknown Source:8)
        at a.i.b.a.g$a$b.b(KClassImpl.kt:168)
        at a.i.b.a.g$a$b.a(KClassImpl.kt:44)
        at a.i.b.a.aa$a.a(ReflectProperties.java:92)
        at a.i.b.a.aa$c.a(ReflectProperties.java:31)
        at a.i.b.a.g$a.h(Unknown Source:8)
        at a.i.b.a.g$a$a.b(KClassImpl.kt:174)
        at a.i.b.a.g$a$a.a(KClassImpl.kt:44)
        at a.i.b.a.aa$a.a(ReflectProperties.java:92)
        at a.i.b.a.aa$c.a(ReflectProperties.java:31)
        at a.i.b.a.g$a.j(Unknown Source:8)
        at a.i.b.a.g.d(KClassImpl.kt:192)
        at a.i.a.c.a(KClasses.kt:90)
        at com.a.a.q.a(Klaxon.kt:268)
        at com.a.a.q.a(Klaxon.kt:264)
        at com.app.whatever.SiteEntryActivity.a(SiteEntryActivity.kt:116)
        at com.app.whatever.SiteEntryActivity.a(SiteEntryActivity.kt:23)
        at com.app.whatever.SiteEntryActivity$c$1$1.run(SiteEntryActivity.kt:98)
        at android.app.Activity.runOnUiThread(Activity.java:6282)
        at com.app.whatever.SiteEntryActivity$c$1.a(SiteEntryActivity.kt:96)
        at com.app.whatever.SiteEntryActivity$c$1.a(SiteEntryActivity.kt:23)
        at com.app.whatever.d$a$1.a(SiteEntryActivity.kt:153)
        at com.app.whatever.d$a$1.a(Unknown Source:6)
        at com.github.kittinunf.fuel.a.e$b.a(Deserializable.kt:40)
        at com.github.kittinunf.fuel.a.e$b.a(Unknown Source:6)
        at com.github.kittinunf.fuel.a.e$d$1.b(Deserializable.kt:72)
        at com.github.kittinunf.fuel.a.e$d$1.a(Unknown Source:0)
        at com.github.kittinunf.fuel.a.n$d.run(Request.kt:263)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

-----

**With Proguard preserving kotlin reflect classes**

```proguard
-keep public class kotlin.reflect.jvm.internal.impl.** { public *; }
```

```kotlin
2018-11-01 13:47:13.352 32665-32665/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.com.whatever, PID: 32665
    com.a.a.r: Couldn't find a toJson() function on converter com.a.a.d@2618262
        at com.a.a.q.a(Klaxon.kt:273)
        at com.a.a.q.a(Klaxon.kt:264)
        at com.app.whatever.SiteEntryActivity.a(SiteEntryActivity.kt:116)
        at com.app.whatever.SiteEntryActivity.a(SiteEntryActivity.kt:23)
        at com.app.whatever.SiteEntryActivity$c$1$1.run(SiteEntryActivity.kt:98)
        at android.app.Activity.runOnUiThread(Activity.java:6282)
        at com.app.whatever.SiteEntryActivity$c$1.a(SiteEntryActivity.kt:96)
        at com.app.whatever.SiteEntryActivity$c$1.a(SiteEntryActivity.kt:23)
        at com.app.whatever.d$a$1.a(SiteEntryActivity.kt:153)
        at com.app.whatever.d$a$1.a(Unknown Source:6)
        at com.github.kittinunf.fuel.a.e$b.a(Deserializable.kt:40)
        at com.github.kittinunf.fuel.a.e$b.a(Unknown Source:6)
        at com.github.kittinunf.fuel.a.e$d$1.a(Deserializable.kt:72)
        at com.github.kittinunf.fuel.a.e$d$1.invoke(Unknown Source:0)
        at com.github.kittinunf.fuel.a.n$d.run(Request.kt:263)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

-----

**With Proguard preserving Klaxon interfaces and classes:**

```proguard
-keep public class kotlin.reflect.jvm.internal.impl.** { public *; }
-keep class com.beust.klaxon.** { *; }
-keep interface com.beust.klaxon.** { *; }
```

```kotlin
2018-11-01 13:50:34.791 471-471/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.com.whatever, PID: 471
    java.lang.ClassCastException: java.lang.String cannot be cast to com.beust.klaxon.JsonObject
        at com.app.whatever.SiteEntryActivity$b.a(SiteEntryActivity.kt:158)
        at com.app.whatever.SiteEntryActivity$b.invoke(SiteEntryActivity.kt:23)
        at kotlin.i.r$a.next(Sequences.kt:174)
        at kotlin.i.e$a.a(Sequences.kt:134)
        at kotlin.i.e$a.hasNext(Sequences.kt:158)
        at kotlin.i.n.a(_Sequences.kt:691)
        at kotlin.i.n.f(_Sequences.kt:721)
        at kotlin.i.n$d.a(_Sequences.kt:556)
        at kotlin.i.p$a.<init>(Sequences.kt:366)
        at kotlin.i.p.a(Sequences.kt:364)
        at kotlin.i.n.a(_Sequences.kt:691)
        at kotlin.i.n.f(_Sequences.kt:721)
        at kotlin.i.n.e(_Sequences.kt:712)
        at com.app.whatever.SiteEntryActivity.m(SiteEntryActivity.kt:130)
        at com.app.whatever.SiteEntryActivity.k(SiteEntryActivity.kt:56)
        at com.app.whatever.SiteEntryActivity.a(SiteEntryActivity.kt:23)
        at com.app.whatever.SiteEntryActivity$c$1$1.run(SiteEntryActivity.kt:99)
        at android.app.Activity.runOnUiThread(Activity.java:6282)
        at com.app.whatever.SiteEntryActivity$c$1.a(SiteEntryActivity.kt:96)
        at com.app.whatever.SiteEntryActivity$c$1.invoke(SiteEntryActivity.kt:23)
        at com.app.whatever.d$a$1.a(SiteEntryActivity.kt:153)
        at com.app.whatever.d$a$1.invoke(Unknown Source:6)
        at com.github.kittinunf.fuel.a.e$b.a(Deserializable.kt:40)
        at com.github.kittinunf.fuel.a.e$b.invoke(Unknown Source:6)
        at com.github.kittinunf.fuel.a.e$d$1.a(Deserializable.kt:72)
        at com.github.kittinunf.fuel.a.e$d$1.invoke(Unknown Source:0)
        at com.github.kittinunf.fuel.a.n$d.run(Request.kt:263)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by cbeust** [comment]
Looks like you need to exclude your Klaxon converter classes from being minified since Klaxon uses reflection to locate `toJson()`.

**Comment by Bombo** [comment]
@cbeust But the sample above only uses the default converter, and that should be handled by the proguard rules supplied up there, is it not? Please let me know if I'm missing something.

**Comment by cbeust** [comment]
Klaxon is somehow trying to convert something.

Maybe set a breakpoint in `toJson` and run a non minified version of your `apk` so you can get a real stack trace.

**Comment by spreelanka** [comment]
@Tarpsvo try adding
```
-keep class kotlin.Metadata { *; }
```

this is what worked with minify for my project:
```
# Klaxon
-keep public class kotlin.reflect.jvm.internal.impl.** { public *; }
-keep class com.beust.klaxon.** { *; }
-keep interface com.beust.klaxon.** { *; }
-keep class kotlin.Metadata { *; }

#data models
-keep class com.example.mydatamodels.** { *;}
```

**Comment by cbeust** [comment]
Note that the error might be coming from a converter outside of the `com.beust.klaxon` package. If you wrote any custom converter, make sure to `keep` these classes too.

**Comment by Bombo** [comment]
@spreelanka That fixed the issue for us. Thanks!
