### ISSUE TITLE
Deeply nested list(List<List<List<Double>>>) does not work

### ISSUE THREAD

**Issue by Avantgarde95** [cbeust/klaxon#224]
`List<List<Double>>` works but `List<List<List<Double>>>` does not work.

The code
```kotlin
import com.beust.klaxon.Klaxon

class Data1(val value: List<List<Double>>) {
    override fun toString() = "[${value.joinToString { "[${it.joinToString()}]" }}]"
}

class Data2(val value: List<List<List<Double>>>) {
    override fun toString() = "[${value.joinToString { "[${it.joinToString { "[${it.joinToString()}]" }}]" }}]"
}

fun main(args: Array<String>) {
    val klaxon = Klaxon()

    val input1 = Data1(listOf(listOf(1.0, 1.1, 1.2)))
    println("input1: $input1")

    val input2 = Data2(listOf(listOf(listOf(1.0, 1.1, 1.2))))
    println("input2: $input2")

    val json1 = klaxon.toJsonString(input1)
    println("json1: $json1")

    val json2 = klaxon.toJsonString(input2)
    println("json2: $json2")

    val output1 = klaxon.parse<Data1>(json1)
    println("output1: ${output1.toString()}")

    val output2 = klaxon.parse<Data2>(json2)
    println("output2: ${output2.toString()}")
}
```
gives
```
input1: [[1.0, 1.1, 1.2]]
input2: [[[1.0, 1.1, 1.2]]]
json1: {"value" : [[1.0, 1.1, 1.2]]}
json2: {"value" : [[[1.0, 1.1, 1.2]]]}
output1: [[1.0, 1.1, 1.2]]
Exception in thread "main" java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
	at com.beust.klaxon.DefaultConverter.fromCollection(DefaultConverter.kt:115)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:29)
	at com.beust.klaxon.JsonObjectConverter.retrieveKeyValues(JsonObjectConverter.kt:79)
	at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:28)
	at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:200)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:30)
	at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:247)
	at MainKt.main(Main.kt:38)
```

**Comment by cbeust** [comment]
This worked right out of the bat for me with the current version:

```
input1: [[1.0, 1.1, 1.2]]
input2: [[[1.0, 1.1, 1.2]]]
json1: {"value" : [[1.0, 1.1, 1.2]]}
json2: {"value" : [[[1.0, 1.1, 1.2]]]}
output1: [[1.0, 1.1, 1.2]]
output2: [[[1.0, 1.1, 1.2]]]
```
