### ISSUE TITLE
IllegalAccessException when Klaxon forces BigInteger conversion by itself

### ISSUE THREAD

**Issue by GoodforGod** [cbeust/klaxon#236]
We have a class:
```Kotlin
data class Poke(
    val block: Long = 0L,
    val value: BigDecimal = BigDecimal.ZERO // Could be String/Long/Int/doesntmatter
)
```
We have a JSON:
```JSON
[
      {          
                "block": 7102460,
                "value": 114470000000000000000
       },
       {
                "block": 7102393,
                "value": 114455000000000000000
       }
]
```

So when we try to serialize it like:
```Kotlin
val poke = Klaxon().parse<Poke>(json)
```

**IllegalAccessException** error occurs:
```Java
kotlin.reflect.full.IllegalCallableAccessException: java.lang.IllegalAccessException: Class kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter can not access a member of class java.math.BigInteger with modifiers "final"

	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:224)
	at com.beust.klaxon.JsonValue$Companion.propertiesAndValues(JsonValue.kt:179)
	at com.beust.klaxon.JsonValue.convertToJsonObject(JsonValue.kt:150)
	at com.beust.klaxon.JsonValue.<init>(JsonValue.kt:141)
	at com.beust.klaxon.JsonObjectConverter.retrieveKeyValues(JsonObjectConverter.kt:185)
	at com.beust.klaxon.JsonObjectConverter.initIntoUserClass(JsonObjectConverter.kt:67)
	at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:32)
	at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:219)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:30)
	at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:294)
```

Klaxon forces itself to somehow convert value to BigInteger without success, even if there aren't any BigInteger field, not sure what behavior it is, even if I try to do something like this with custom BigDecimal converter:
```Kotlin
Klaxon().fieldConverter(KlaxonBigDecimal::class, KlaxonConverters.bigDecimalConverter)
```
Still no success.
Not sure why it forces its self and behaves so it can't just cast value as a String.
If value will be not **114455000000000000000** but **1144550000**, works fine.

JDK 1.8.0_181
Kotlin '1.3.10'
Dependency:
```Gradle
sourceCompatibility = 1.8
targetCompatibility = 1.8

api group: 'com.beust', name: 'klaxon', version: '5.0.4'
implementation "org.jetbrains.kotlin:kotlin-reflect:1.3.10"
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.10"
```

**Comment by GoodforGod** [comment]
Yeah, I was actually using *parseArray()* for array and *parse()* for single, just my mistake in issue description.
Thanks.

**Comment by Al-p-i** [comment]
BigInteger is still an issue in 5.0.5
`data class Account(val id: String, var amount: BigInteger)`
fails with
```
Exception in thread "main" com.beust.klaxon.KlaxonException: Unable to instantiate Lab with parameters [amount: 0, id: caa58525-5d1d-4f13-9081-bf30d1544057]
	at com.beust.klaxon.JsonObjectConverter.initIntoUserClass(JsonObjectConverter.kt:94)
	at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:32)
	at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:209)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:31)
	at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:294)
	at BillingServiceTestKt.main(BillingServiceTest.kt:66)
```
May be because BigInteger does not really have public constructor(long)
