### ISSUE TITLE
Occasionally when parsing JSON there will be a null PathMatcher

### ISSUE THREAD

**Issue by alexanderdrm** [cbeust/klaxon#251]
On version 5.0.5 the following error happens occasionally, inconsistently when parsing.
There are custom Converters registered but no custom PathMatchers, in case that is relevant.

java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.beust.klaxon.PathMatcher.pathMatches(java.lang.String)' on a null object reference
       at com.beust.klaxon.World.foundValue$klaxon(World.kt:97)
       at com.beust.klaxon.KlaxonParser$1$5.invoke(KlaxonParser.kt:105)
       at com.beust.klaxon.KlaxonParser$1$5.invoke(KlaxonParser.kt:9)
       at com.beust.klaxon.StateMachine.next(StateMachine.kt:20)
       at com.beust.klaxon.KlaxonParser.fullParseLoop(KlaxonParser.kt:63)
       at com.beust.klaxon.KlaxonParser.parse(KlaxonParser.kt:25)
       [app code calls .parse]

**Comment by cbeust** [comment]
Any way to reproduce this consistently?

**Comment by alexanderdrm** [comment]
I have not discovered any way to reproduce the issue consistently, if I do I'll update this issue.
