### ISSUE TITLE
Parsing of polymorphic JSON objects fails when one or more involved fields are named by annotation

### ISSUE THREAD

**Issue by nerd** [cbeust/klaxon#263]
Hi!

I am using Klaxon 5.0.5 on Kotlin 1.3.31 with the following code samples:

```kotlin
fun main() {
    val str = """
        {
            "t": null,
            "op": 10,
            "d": { "heartbeat_interval": 41250 }
        }
    """.trimIndent()

    Klaxon().parse<GatewayResponsePayload>(str)?.let { payload ->
        println(payload) // will show deserialised object, but with generic GatewayResponse object instead of ServerHello.
        println(payload.data is ServerHello) // will be false
    }
}
```

```kotlin
data class GatewayResponsePayload(
    @TypeFor(field = "data", adapter = DataTypeAdapter::class)
    @Json("op") val opCode: Int?,
    @Json("t") val type: String?,
    @Json("d") val data: GatewayResponse
)

open class GatewayResponse

data class ServerHello(@Json("heartbeat_interval") val heartbeatInterval: Long) : GatewayResponse()

class DataTypeAdapter : TypeAdapter<GatewayResponse> {
    override fun classFor(type: Any): KClass<out GatewayResponse> {
        (type as Int?).apply {
            println(this)
            return when (this) {
                10 ->  {
                    println("Hello, this class is being parsed properly!")
                    ServerHello::class
                }
                else -> throw RuntimeException("No type for this opcode.")
            }
        }
    }
}
```

If either of the fields involved in the polymorphism (in this case `opCode` and `data`) have an alias (as shown in the provided code sample), Klaxon will fail, lacking output from both Klaxon itself as well as the print statements in the `DataTypeAdapter` class. If, however, only the field `opCode` has an alias, the following exception will be thrown:

```
Exception in thread "main" kotlin.TypeCastException: null cannot be cast to non-null type kotlin.Any
	at com.beust.klaxon.JsonObjectConverter.calculatePolymorphicClass(JsonObjectConverter.kt:207)
	at com.beust.klaxon.JsonObjectConverter.retrieveKeyValues(JsonObjectConverter.kt:180)
	at com.beust.klaxon.JsonObjectConverter.initIntoUserClass(JsonObjectConverter.kt:67)
	at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:32)
	at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:209)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:31)
	at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:294)
```

**Comment by cbeust** [comment]
I can't reproduce this for now. I had to rewrite your code as follows (the compiler complains otherwise):

```
class DataTypeAdapter : TypeAdapter<GatewayResponse> {
    override fun classFor(type: Any): KClass<out GatewayResponse> {
        if (type as Int? == 10) return ServerHello::class
        else throw RuntimeException("No type for this opcode.")
    }
}
```

and when I run it, I get:

```
GatewayResponsePayload(opCode=10, type=null, data=com.beust.klaxon.GatewayResponse@6f2cb653)
false
```

Can you provide code that fails?

**Comment by nerd** [comment]
That code is a failure case, unless I’m misunderstanding something. `data` should be an instance of `ServerHello`, should it not? That’s what I meant when I said there was no output. Even if you add a `println` call within the `classFor` override, it won’t print.

If, however, you’re only looking for exceptions, you can remove the `@Json` on the `opCode` field and fix up the actual JSON to match. (I’m unfortunately away from my computer right now otherwise I’d paste an implementation like that here)

**Comment by cbeust** [comment]
Ok I see the problem now, thanks!

**Comment by Mijyuoon** [comment]
Still having this issue, are there any estimates for a fix?
