### ISSUE TITLE
Parsing a sealed class heirarchy of objects

### ISSUE THREAD

**Issue by Octogonapus** [cbeust/klaxon#268]
Say I have a sealed class like this, which only contains objects:
```kotlin
sealed class FooSealed {
    object Bar : FooSealed()
    object Baz : FooSealed()
}
```

I try to convert it in and out of JSON:
```kotlin
internal class KlaxonTest {

    private val klaxon = Klaxon()

    @Test
    fun `test converting object`() {
        val jsonString = klaxon.toJsonString(FooSealed.Bar)
        println(jsonString)
        val barFromJson = klaxon.parse<FooSealed>(jsonString)
        println(barFromJson)
    }
}
```

`jsonString` is printed as `{}` (it's empty). So of course Klaxon fails to parse it:
```
com.beust.klaxon.KlaxonException: Unable to instantiate FooSealed with parameters []

	at com.beust.klaxon.JsonObjectConverter.initIntoUserClass(JsonObjectConverter.kt:94)
	at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:32)
	at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:209)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:31)
	at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:294)
```

Can we do better than this for this case? I think Klaxon should be able to handle sealed classes out of the box. If you tell me where the problem is, I would be happy to PR the change.

**Comment by Octogonapus** [comment]
FWIW, I have written a custom converter to do this:
```kotlin
class NestedObjectConverter(cls: KClass<*>) : Converter {

    private val allClasses by lazy {
        allNestedSubclasses(cls) + cls
    }

    override fun canConvert(cls: Class<*>) = allClasses.map { it.java }.contains(cls)

    override fun fromJson(jv: JsonValue): Any? {
        val objectName = jv.objString("name")
        return allClasses.firstOrNull { it.qualifiedName == objectName }?.objectInstance
    }

    override fun toJson(value: Any): String {
        require(value::class in allClasses)
        return """{"name": "${value::class.qualifiedName}"}"""
    }
}
```
