### ISSUE TITLE
can I use .parse<Test<Test2>>(json) ?

### ISSUE THREAD

**Issue by gai00** [cbeust/klaxon#274]
I'm learning Android, and new on using Klaxon.
I think it should be work...
What did I miss?

gradle(tried, yes or no both not working)
```
...
implementation 'org.jetbrains.kotlin:kotlin-reflect:1.3.40'
...
```

jsonData
```json
{
    "data": {
        "value": 123
    }
}
```
code
```kotlin
data class Test<T>(
    val data: T
)
data class Test2(
    val value: Int
)
...
{
    ...
    val result = Klaxon().parse<Test<Test2>>(json)
}
```
Error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 16014
    java.lang.ClassCastException: libcore.reflect.TypeVariableImpl cannot be cast to java.lang.Class
        at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:205)
        at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:31)
        at com.beust.klaxon.JsonObjectConverter.retrieveKeyValues(JsonObjectConverter.kt:185)
        at com.beust.klaxon.JsonObjectConverter.initIntoUserClass(JsonObjectConverter.kt:67)
        at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:32)
        at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:209)
        at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:31)
        at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:294)
        at com.example.myapplication.MainActivity$onCreate$2$1.invokeSuspend(MainActivity.kt:95)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:6274)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by cbeust** [comment]
No, that type is lost to erasure. You need to make `Test` non generic.
