### ISSUE TITLE
"Exception in thread "main" com.beust.klaxon.KlaxonException: Should never happen" parsing large numbers

### ISSUE THREAD

**Issue by lpar** [cbeust/klaxon#278]
```kotlin
val BigDecimalConverter = object : Converter {
  override fun canConvert(cls: Class<*>): Boolean = cls == BigDecimal::class.java

  override fun fromJson(jv: JsonValue): Any? {
    println("JsonValue = ${jv}")
    return BigDecimal.ZERO
  }

  override fun toJson(value: Any): String {
    TODO("not implemented")
  }
}

fun main() {
  data class Economy (
    val nationalDebt : BigDecimal
  )
  val json = """{ "nationalDebt" : 9007199254740991 }"""
  val klaxon = Klaxon().converter(BigDecimalConverter)
  val obj = klaxon.parse<Economy>(json)
  println("${obj}")
}
```

Result:

```
Exception in thread "main" com.beust.klaxon.KlaxonException: Should never happen
	at com.beust.klaxon.JsonValue.toString(JsonValue.kt:167)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at serialization.MainKt$BigDecimalConverter$1.fromJson(main.kt:57)
	at com.beust.klaxon.JsonObjectConverter.retrieveKeyValues(JsonObjectConverter.kt:185)
	at com.beust.klaxon.JsonObjectConverter.initIntoUserClass(JsonObjectConverter.kt:67)
	at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:32)
	at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:204)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:29)
	at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:294)
	at serialization.MainKt.main(main.kt:93)
	at serialization.MainKt.main(main.kt)
```

`2147483647` works, `2147483648` doesn't, `2147483648.0` is fine, so it seems Klaxon fails on any JSON number which looks like an integer but doesn't fit into an int. Since JSON lacks the concept of integers, I think this must be classed a bug.

(In fact the JSON spec apparently doesn't specify any limit on number sizes, but it would seem reasonable to me to support anything that ECMAScript supports, which means integers up to 9007199254740991.)

**Comment by cbeust** [comment]
Fixed in 5.0.9.

**Comment by lpar** [comment]
By the way, thanks a lot for this library. I was finding it impossible to get polymorphic deserialization to work with Moshi, but got it working with Klaxon without too much trouble.

**Comment by cbeust** [comment]
Thanks for the kind words, @lpar!
