### ISSUE TITLE
Can't map array of JSON objects to a class containing primitives

### ISSUE THREAD

**Issue by ejektaflex** [cbeust/klaxon#77]
Attempting to map a JSON file containing an array of objects results in this error:

```
Exception in thread "main" kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Call is not yet supported for this function: private constructor Double() defined in kotlin.Double[DeserializedClassConstructorDescriptor@3232a28a] (member = null)
	at kotlin.reflect.jvm.internal.KFunctionImpl$caller$2.invoke(KFunctionImpl.kt:89)
	at kotlin.reflect.jvm.internal.KFunctionImpl$caller$2.invoke(KFunctionImpl.kt:34)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
	at kotlin.reflect.jvm.internal.KFunctionImpl.getCaller(KFunctionImpl.kt)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:107)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod(KCallableImpl.kt:149)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:111)
	at com.beust.klaxon.Klaxon$fromJsonObject$2.invoke(Klaxon.kt:277)
	at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:294)
	at com.beust.klaxon.DefaultConverter.convertValue(DefaultConverter.kt:110)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:13)
	at com.beust.klaxon.Klaxon$fromJsonObject$1.invoke(Klaxon.kt:241)
	at com.beust.klaxon.Klaxon$fromJsonObject$2.invoke(Klaxon.kt:263)
	at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:294)
	at MainKt.main(Main.kt:29)
```

[Here are the source files](https://gist.github.com/ejektaflex/66b2cd09be90bfb1977a293580f411d3) that I used to set up this situation.

JSON file in question:
```
[
  {
    "date": "2018/01/10",
    "close": 0.25,
    "volume": 500000,
    "open": 0.5,
    "high": 0.5,
    "low": 0.25
  }
]
```

**Comment by cbeust** [comment]
Fixed in 2.0.6.
