### ISSUE TITLE
Adding public variables without JSON equivalent causes NoSuchFieldException

### ISSUE THREAD

**Issue by ejektaflex** [cbeust/klaxon#78]
Adding variables that do not map to JSON fields causes a NoSuchFieldException, as shown in [these files](https://gist.github.com/ejektaflex/4fee26c0fc849b8419b30aa9ffb4071f).

```
Exception in thread "main" java.lang.NoSuchFieldException: change
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at com.beust.klaxon.Klaxon$fromJsonObject$1.invoke(Klaxon.kt:232)
	at com.beust.klaxon.Klaxon$fromJsonObject$2.invoke(Klaxon.kt:264)
	at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:301)
	at StockHelper.data(Stocky.kt:41)
	at MainKt.main(Main.kt:3)
```

**Comment by cbeust** [comment]
Should be fixed in 2.0.7: just add `@Json(ignored = true)` to properties that Klaxon should ignore.
