### ISSUE TITLE
Klaxon cannot deserialize to or from raw strings

### ISSUE THREAD

**Issue by oharaandrew314** [cbeust/klaxon#86]
In Klaxon `2.0.10`:
- If an object serializes to a string, it cannot be deserialized
- cannot deserialize a list of strings

/**
    data class Person(val id: String, val firstName: String)
    class PersonConverter: Converter<Person> {
        override fun toJson(value: Person) = "${value.id}:${value.firstName}"
        override fun fromJson(jv: JsonValue) = jv.string?.let {
            val (id, firstName) = it.split(":")
            Person(id, firstName)
        } ?: throw KlaxonException("Invalid Person: $jv")
    }

     * com.beust.klaxon.KlaxonException: No state found: IN_ARRAY COLON

    at com.beust.klaxon.StateMachine.next(StateMachine.kt:22)
    at com.beust.klaxon.Parser.fullParseLoop(Parser.kt:59)
    at com.beust.klaxon.Parser.parse(Parser.kt:29)
    at com.prontoforms.pcns.auth.authorizer.MethodArnUnitTest.deserializeStringListToObject(MethodArnUnitTest.kt:66)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
     */
    @Test
    fun deserializeStringListToObjectList() {
        val mapper = Klaxon().converter(PersonConverter())
        val obj = listOf(Person("1", "John"))

        val jv = mapper.toJsonString(obj)
        Assert.assertThat(jv, CoreMatchers.equalTo("[1:John]")) // Passes
        Assert.assertThat(mapper.parse(jv), CoreMatchers.equalTo(obj)) // Fails
    }

    /**
     * com.beust.klaxon.KlaxonException: No state found: IN_FINISHED_VALUE COLON

    at com.beust.klaxon.StateMachine.next(StateMachine.kt:22)
    at com.beust.klaxon.Parser.fullParseLoop(Parser.kt:59)
    at com.beust.klaxon.Parser.parse(Parser.kt:29)
    at com.prontoforms.pcns.auth.authorizer.MethodArnUnitTest.deserializeStringToObject(MethodArnUnitTest.kt:69)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
     */
    @Test
    fun deserializeStringToObject() {
        val mapper = Klaxon().converter(PersonConverter())
        val obj = Person("1", "John")

        val jv = mapper.toJsonString(obj)
        Assert.assertThat(jv, CoreMatchers.equalTo("1:John")) // Passes
        Assert.assertThat(mapper.parse(jv), CoreMatchers.equalTo(obj))  // Fails
    }

    /**
     * java.lang.ClassCastException: com.beust.klaxon.JsonArray cannot be cast to com.beust.klaxon.JsonObject

    at com.prontoforms.pcns.auth.authorizer.MethodArnUnitTest.deserializeRawStringList(MethodArnUnitTest.kt:142)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
     */
    @Test
    fun deserializeStringListToStringList() {
        val obj = listOf("foo", "bar", "baz")
        val mapper = Klaxon()

        val jv = mapper.toJsonString(obj)
        Assert.assertThat(jv, CoreMatchers.equalTo("[\"foo\", \"bar\", \"baz\"]")) // Passes
        Assert.assertThat(mapper.parse(jv), CoreMatchers.equalTo(obj)) // Fails
    }

**Comment by cbeust** [comment]
Your toJson function needs to surround its result with braces.

**Comment by oharaandrew314** [comment]
So, is it invalid to have a structure of
```
val people = listOf(person1, person2)
```

serialize to
```
["1:John", "2:Jane"]
```
?

**Comment by cbeust** [comment]
Correct, that's invalid JSON.
