### ISSUE TITLE
Klaxon cannot deserialize JSON array at root of the document

### ISSUE THREAD

**Issue by oharaandrew314** [cbeust/klaxon#87]
It is completely valid for a JSON array to be at the root of a JSON document.  `jsonlint.com` confirms this, and the standard at `json.org` does not forbid it.  However, Klaxon `2.0.10` seems to require that documents start with an object.

For example, this is valid json:
```[1, 2, 3]```

Here's a test example:

```
    /**
     *
    java.lang.ClassCastException: com.beust.klaxon.JsonArray cannot be cast to com.beust.klaxon.JsonObject

    at com.prontoforms.pcns.auth.authorizer.MethodArnUnitTest.serializeList(MethodArnUnitTest.kt:102)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
     */
    @Test
    fun serializeList() {
        val obj = listOf(1,2,3)
        val mapper = Klaxon()

        val jv = mapper.toJsonString(obj)
        Assert.assertThat(jv, CoreMatchers.equalTo("[1, 2, 3]"))
        Assert.assertThat(mapper.parse(jv), CoreMatchers.equalTo(obj))
    }
```

**Comment by cbeust** [comment]
`parse()` returns a `JsonObject`. If you want to parse an array, you need to call

```
mapper.parseArray<Integer>(jv)
```

**Comment by oharaandrew314** [comment]
Whoops.  Sorry!
